services:
  sharding-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sharding-service
    ports:
      - "6000:6000"  # gRPC port
      - "6001:6001"  # HTTP metrics/health check
    volumes:
      - ./:/app
      - ./proto:/app/proto
    networks:
      - sharding-network
    environment:
      - APP_ENV=development
      - RR_CONFIG=rr
    restart: unless-stopped

networks:
  sharding-network:
    driver: bridge